version: '3'

services:
  web1:
    image: nginx
    container_name: web1
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - web_network

  web2:
    image: nginx
    container_name: web2
    volumes:
      - ./web:/usr/share/nginx/html	#./web2 en caso de diferenciar index.html 
    networks:
      - web_network

  balancer:
    image: nginx
    container_name: balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" #si ya se está usando el puerto 80 de la máquina real, cambiar el primer 80 por otro puerto
    networks:
      - web_network

networks:
  web_network:
    driver: bridge