/* NO SE PUEDE por que el telefono es repetido 
INSERT INTO CLIENTES_2
(ID_CLIENTE, NOM_CLI, DIRECCION, LOCALIDAD, TELEFONO)
VALUES('CLI_0004','Espino','C/Peral 4','Torrejon de Ardoz',917805678); */

INSERT INTO PEDIDOS_2
(ID_PEDIDO, ID_CLIENTE, FECHA, IMPORTE)
VALUES('PED_1002','CLI_0001','14/02/12',NULL);

INSERT INTO PLATOS_2
(ID_PLATO, DEC_PLATO, INGREDIENTES, PRECIO)
VALUES('PLA_0003','Pollo','Pollo y patatas',8);

/* NO SE PUEDE POR QUE NO TENEMOS NUM_PLATOS
INSERT INTO DETALLE_PEDIDO_2
(ID_PEDIDO, ID_PLATO, NUM_PLATOS)
VALUES('PED_1003','PLA_0001');
*/

INSERT INTO PEDIDOS_2
(ID_PEDIDO, ID_CLIENTE, FECHA, IMPORTE)
VALUES('PED_1004','CLI_0004','14/02/12',1750);

INSERT INTO DETALLE_PEDIDO_2
(ID_PEDIDO, ID_PLATO, NUM_PLATOS)
VALUES('PED_1001','PLA_0001',6);

INSERT INTO PLATOS_2
(ID_PLATO, DEC_PLATO, INGREDIENTES, PRECIO)
VALUES('PLA_0004','Merluza',NULL,17);

/* NO SE PUEDE POR QUE ID_CLIENTE NO PUEDE SER NULL POR QUE ES PK
INSERT INTO CLIENTES_2
(ID_CLIENTE, NOM_CLI, DIRECCION, LOCALIDAD, TELEFONO)
VALUES(NULL,'Lorena','C/Flores 4','Coslada',917899900);
*/