/* 1. CREAR BASE DE DATOS */

CREATE DATABASE TEMA4_PRACTICA2;


/* 2. CREAR TABLAS SOCIOS */

CREATE TABLE SOCIOS_4(
    SOCIO_NO INT(4) PRIMARY KEY,
    APELLIDOS VARCHAR(14) UNIQUE,
    TELEFONO CHAR(9) NOT NULL,
    FECHA_ALTA DATE DEFAULT '2000-01-01',
    DIRECCION VARCHAR(20),
    CODIGO_POSTAL INT(5) 
);

CREATE TABLE prestamos_4(
    num_prestamo INT(4) PRIMARY KEY AUTO_INCREMENT,
    SOCIO_NO INT(4),
    CONSTRAINT FK_SOCIO_NO_4
    FOREIGN KEY PRESTAMOS_4(SOCIO_NO)
    REFERENCES SOCIOS_4(SOCIO_NO)
    /* ON DELETE CASCADE */
    /* ON UPDATE CASCADE */
);


 

/* 3. METER DATO EN TABLA */


INSERT INTO SOCIOS_4
(SOCIO_NO, APELLIDOS, TELEFONO, FECHA_ALTA, DIRECCION, CODIGO_POSTAL)
VALUES(1000, 'LOPEZ SANTOS', '9165643267', '2005-01-08','C.REAL 5', 28400); 


INSERT INTO SOCIOS_4
(SOCIO_NO, APELLIDOS, TELEFONO, FECHA_ALTA, DIRECCION, CODIGO_POSTAL)
VALUES(1001, 'PEREZ CERRO', '918451256', '2005-01-12','C.MAYOR 31', 28400); 


INSERT INTO SOCIOS_4
(SOCIO_NO, APELLIDOS, TELEFONO, FECHA_ALTA, DIRECCION, CODIGO_POSTAL)
VALUES(1002, 'LOPEZ PEREZ', '916543267', '2005-01-18','C.REAL 5', 28400); 


INSERT INTO SOCIOS_4
(SOCIO_NO, APELLIDOS, TELEFONO, FECHA_ALTA, DIRECCION, CODIGO_POSTAL)
VALUES(1003, 'ROMA LEIVA', '', '2005-01-21','C.PANADEROS 9', 28431); 


INSERT INTO SOCIOS_4
(SOCIO_NO, APELLIDOS, TELEFONO, FECHA_ALTA, DIRECCION, CODIGO_POSTAL)
VALUES(1004, 'GOMEZ DURUELO', '918654329', '2005-01-31','C.REAL 15', 28400); 

INSERT INTO SOCIOS_4
(SOCIO_NO, APELLIDOS, TELEFONO, FECHA_ALTA, DIRECCION, CODIGO_POSTAL)
VALUES(1005, 'PEÑA MAYOR', '91851526', '2000-01-01','C.LARGA 31', 28431); 

/* METER DATO EN TABLA PRESTAMOS */

INSERT INTO PRESTAMOS_4
(num_prestamos, SOCIO_NO)
VALUES ( 1, 1001);

INSERT INTO PRESTAMOS_4
(num_prestamos, SOCIO_NO)
VALUES ( 2, 1002);

INSERT INTO PRESTAMOS_4
(num_prestamos, SOCIO_NO)
VALUES ( 3, 1003);


/* 4. BORRAR LA TABLA SOCIOS A SOCIO_NO = 1003 */ 
DELETE FROM SOCIOS_4
WHERE SOCIO_NO = 1003;

/* 5. MODIFICAR LA TABLA SOCIOS DE 1002 A 1222 */
UPDATE SOCIOS_4
/* ponemos primero el valor que al que lo queremos cambiar y en el where el valor que esta en la tabla */
SET SOCIO_NO = 1222
WHERE SOCIO_NO = 1002; 

/* 6. Modifica de la tabla socios_4 el codigo postal por 28444 de los socios que viven en "C.REAL"
 y su primerapellido es "LOPEZ". Si no es posible explica por qué  */ 
UPDATE SOCIOS_4
SET codigo_postal = 2844
WHERE direccion LIKE 'C.REAL' AND apellido LIKE 'LOPEZ';

/* 7. */
/* 
NO 
Por que esta activado el autocommit
*/

/* 8. DESACTIVA EL AUTO COMMIT */ 
SET AUTOCOMMIT = 0;

/* 9. Borra de la tabla socios_4 a todos los socios que entraron antes del 01-02-2000. Si no es posible explica porqué */ 
DELETE FROM SOCIOS_4
WHERE FECHA_ALTA < '2000-02-01';

/* 10. Modifica de la tabla socios_4 la dirección y el código postal del socio_no = '1003' por "C.LORCA 44" y"28999". Si no es posible explica por qué.*/ 


/* 11.  */
SI
EJECUTAMOS EL COMANDO ROLLBACK

/* 12. Modifica de la tabla socios_4 a socio_no = 1003 por socio_no = 1333. Si no es posible explica por qué */ 
UPDATE SOCIOS_4
SET SOCIO_NO = 1333
WHERE SOCIO_NO = 1003;

/* NO ES POSIBLE POR QUE SOCIO_NO NO EXISTE EN LA TABLA SOCIOS_4 */

/* 13.  */
el auto commit esta desactivado

y para hacerlos permanentes es usando el comando commit 
